"""Property definitions"""

from __future__ import annotations

from dataclasses import dataclass

from .const import (
    UNIT_NODE,
    UNIT_NODECONFIGURATION,
    UNIT_TEMPHUMCONTROL,
    UNIT_VENTILATIONCONFIG,
    PdoType,
)


@dataclass
class Property:
    """Dataclass for a Property"""

    unit: int
    subunit: int
    property_id: int
    property_type: int


# --- NODE (general node information) ---
PROPERTY_SERIAL_NUMBER = Property(UNIT_NODE, 0x01, 0x04, PdoType.TYPE_CN_STRING)
PROPERTY_FIRMWARE_VERSION = Property(UNIT_NODE, 0x01, 0x06, PdoType.TYPE_CN_UINT32)
PROPERTY_MODEL = Property(UNIT_NODE, 0x01, 0x08, PdoType.TYPE_CN_STRING)
PROPERTY_ARTICLE = Property(UNIT_NODE, 0x01, 0x0B, PdoType.TYPE_CN_STRING)
PROPERTY_COUNTRY = Property(UNIT_NODE, 0x01, 0x0D, PdoType.TYPE_CN_STRING)
PROPERTY_NAME = Property(UNIT_NODE, 0x01, 0x14, PdoType.TYPE_CN_STRING)

# --- NODECONFIGURATION ---
PROPERTY_MAINTAINER_PASSWORD = Property(UNIT_NODECONFIGURATION, 0x01, 0x03, PdoType.TYPE_CN_STRING)
PROPERTY_ORIENTATION = Property(UNIT_NODECONFIGURATION, 0x01, 0x04, PdoType.TYPE_CN_UINT8)  # 0=left, 1=right

# --- TEMPHUMCONTROL (target temperatures / sensor ventilation) ---
PROPERTY_RMOT_HEATING_PERIOD = Property(UNIT_TEMPHUMCONTROL, 0x01, 0x02, PdoType.TYPE_CN_INT16)  # 180 -> 18.0 °C
PROPERTY_RMOT_COOLING_PERIOD = Property(UNIT_TEMPHUMCONTROL, 0x01, 0x03, PdoType.TYPE_CN_INT16)  # 200 -> 20.0 °C
PROPERTY_SENSOR_VENTILATION_TEMP_PASSIVE = Property(UNIT_TEMPHUMCONTROL, 0x01, 0x04, PdoType.TYPE_CN_UINT32)
PROPERTY_SENSOR_VENTILATION_HUMIDITY_COMFORT = Property(UNIT_TEMPHUMCONTROL, 0x01, 0x06, PdoType.TYPE_CN_UINT32)
PROPERTY_SENSOR_VENTILATION_HUMIDITY_PROTECTION = Property(UNIT_TEMPHUMCONTROL, 0x01, 0x07, PdoType.TYPE_CN_UINT32)
PROPERTY_TARGET_TEMPERATURE_HEATING = Property(UNIT_TEMPHUMCONTROL, 0x01, 0x0A, PdoType.TYPE_CN_INT16)  # warm profile, 230 -> 23.0 °C
PROPERTY_TARGET_TEMPERATURE_NORMAL = Property(UNIT_TEMPHUMCONTROL, 0x01, 0x0B, PdoType.TYPE_CN_INT16)  # normal profile, 210 -> 21.0 °C
PROPERTY_TARGET_TEMPERATURE_COOLING = Property(UNIT_TEMPHUMCONTROL, 0x01, 0x0C, PdoType.TYPE_CN_INT16)  # cool profile, 190 -> 19.0 °C

# --- VENTILATIONCONFIG ---
PROPERTY_FLOW_AWAY = Property(UNIT_VENTILATIONCONFIG, 0x01, 0x03, PdoType.TYPE_CN_INT16)  # m³/h
PROPERTY_FLOW_LOW = Property(UNIT_VENTILATIONCONFIG, 0x01, 0x04, PdoType.TYPE_CN_INT16)  # m³/h
PROPERTY_FLOW_MEDIUM = Property(UNIT_VENTILATIONCONFIG, 0x01, 0x05, PdoType.TYPE_CN_INT16)  # m³/h
PROPERTY_FLOW_HIGH = Property(UNIT_VENTILATIONCONFIG, 0x01, 0x06, PdoType.TYPE_CN_INT16)  # m³/h
PROPERTY_ALTITUDE = Property(UNIT_VENTILATIONCONFIG, 0x01, 0x07, PdoType.TYPE_CN_UINT8)  # 0=0-500, 1=500-1000, 2=1000-1500, 3=1500-2000 m
PROPERTY_VENTILATION_CONTROL_MODE = Property(UNIT_VENTILATIONCONFIG, 0x01, 0x09, PdoType.TYPE_CN_UINT8)  # 0=flow control, 1=constant flow
PROPERTY_BATHROOM_SWITCH_ACTIVATION_DELAY = Property(UNIT_VENTILATIONCONFIG, 0x01, 0x0B, PdoType.TYPE_CN_INT16)  # seconds
PROPERTY_BATHROOM_SWITCH_DEACTIVATION_DELAY = Property(UNIT_VENTILATIONCONFIG, 0x01, 0x0C, PdoType.TYPE_CN_UINT8)  # minutes
PROPERTY_BATHROOM_SWITCH_MODE = Property(UNIT_VENTILATIONCONFIG, 0x01, 0x0D, PdoType.TYPE_CN_UINT8)  # 0=fixed, 1=mirrored
PROPERTY_UNBALANCE = Property(UNIT_VENTILATIONCONFIG, 0x01, 0x12, PdoType.TYPE_CN_INT16)  # -99 -> -9.9 %
